export {
  pairSwissRound,
  buildPlayerStates,
  computeStandings,
  computeSectionStandings,
  diagnosePairings,
  colorPreference,
  colorImbalance,
  type EnginePlayer,
  type PastGame,
  type PairingBoard,
  type PairingInput,
  type PairingOutput,
  type PlayerState,
  type PlayerId,
  firstRoundMissingResults,
} from './swiss.js';

export {
  pairRound,
  STYLE_META,
  UnsupportedPairingStyleError,
} from './registry.js';

export {
  createSimulation,
  generatePlayers,
  pairNextRound,
  applyPendingResults,
  runAllRounds,
  getSimulationStandings,
  getSimulationDiagnostics,
  filterPlayersByCategory,
  createRng,
  simulateResult,
  expectedScore,
  type SimulatorConfig,
  type SimPlayer,
  type SimRound,
  type SimBoard,
  type SimCategory,
  type SimulationState,
  type StandingRow,
  type ResultMode,
} from './simulator.js';
